# Generated by Django 5.0.6 on 2024-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=256)),
                ('role', models.BooleanField()),
                ('creationDate', models.DateField()),
            ],
        ),
    ]
