# Generated by Django 5.0.6 on 2024-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
